version: "3.8"

services:

  db:
    image: postgres
    container_name: db
    env_file:
      - ./db/.env.db
    # volumes:
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./db/map.sql:/docker-entrypoint-initdb.d/map.sql
    ports:
      - "7700:5432"
    restart: unless-stopped
    networks:
      map:
        null

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   volumes:
  #     - ./backend:/backend
  #   depends_on:
  #     - db
  #   command: bash -c "npm run setupdb && npm run dev"
  #   ports:
  #     - "7000:7000"
  #   restart: unless-stopped
  #   networks:
  #     map:
  #       null

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   volumes:
  #     - ./frontend:/frontend
  #   ports:
  #     - "7777:7777"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  #   networks:
  #     map:
  #       null

networks:
  map:
    driver: bridge