version: "3.5"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    command: bash -c "npm start"
    ports:
      - "7000:7000"
    restart: unless-stopped
    networks:
      map: null

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    command: bash -c "npm start"
    ports:
      - "7777:7777"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      map: null

volumes:
  build_folder: null

networks:
  map:
    driver: bridge